// default package
// Generated Mar 4, 2023, 11:48:59 PM by Hibernate Tools 6.0.0.Alpha3
package iti.jets.marketplace.models;

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,catalog="marketplacedb"
)
public class Address  implements java.io.Serializable {


     private Integer addressId;
     private String country;
     private String area;
     private String street;
     private Integer buildNo;
     private Integer floorNo;
     private Set<User> users = new HashSet<User>(0);

    public Address() {
    }

	
    public Address(String country, String area, String street) {
        this.country = country;
        this.area = area;
        this.street = street;
    }
    public Address(String country, String area, String street, Integer buildNo, Integer floorNo, Set<User> users) {
       this.country = country;
       this.area = area;
       this.street = street;
       this.buildNo = buildNo;
       this.floorNo = floorNo;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="addressId", unique=true, nullable=false)
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    
    @Column(name="country", nullable=false, length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="area", nullable=false, length=45)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="street", nullable=false, length=45)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="buildNo")
    public Integer getBuildNo() {
        return this.buildNo;
    }
    
    public void setBuildNo(Integer buildNo) {
        this.buildNo = buildNo;
    }

    
    @Column(name="floorNo")
    public Integer getFloorNo() {
        return this.floorNo;
    }
    
    public void setFloorNo(Integer floorNo) {
        this.floorNo = floorNo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


