// default package
// Generated Mar 10, 2023, 1:36:13 PM by Hibernate Tools 6.0.0.Alpha3
package iti.jets.marketplace.models;

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import iti.jets.marketplace.models.Roles;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name="authorities"
    ,catalog="marketplacedb"
)
public class Authorities  implements java.io.Serializable {


     private int autoritiesId;
     private String name;
     private String describtion;
     private Set<Roles> roleses = new HashSet<Roles>(0);

    public Authorities() {
    }

	
    public Authorities(int autoritiesId) {
        this.autoritiesId = autoritiesId;
    }
    public Authorities(int autoritiesId, String name, String describtion, Set<Roles> roleses) {
       this.autoritiesId = autoritiesId;
       this.name = name;
       this.describtion = describtion;
       this.roleses = roleses;
    }
   
     @Id 

    
    @Column(name="autoritiesId", unique=true, nullable=false)
    public int getAutoritiesId() {
        return this.autoritiesId;
    }
    
    public void setAutoritiesId(int autoritiesId) {
        this.autoritiesId = autoritiesId;
    }

    
    @Column(name="name", length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="describtion", length=255)
    public String getDescribtion() {
        return this.describtion;
    }
    
    public void setDescribtion(String describtion) {
        this.describtion = describtion;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="roles_has_authorities", catalog="marketplacedb", joinColumns = { 
        @JoinColumn(name="authorities_autoritiesId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Roles_rolesId", nullable=false, updatable=false) })
    public Set<Roles> getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set<Roles> roleses) {
        this.roleses = roleses;
    }




}


