// default package
// Generated Mar 4, 2023, 11:48:59 PM by Hibernate Tools 6.0.0.Alpha3
package iti.jets.marketplace.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name="image"
    ,catalog="marketplacedb"
)
public class Image  implements java.io.Serializable {


     private Integer imageId;
     private Product product;
     private String imageUrl;
     private String imageDesc;

    public Image() {
    }

	
    public Image(Product product) {
        this.product = product;
    }
    public Image(Product product, String imageUrl, String imageDesc) {
       this.product = product;
       this.imageUrl = imageUrl;
       this.imageDesc = imageDesc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="imageId", unique=true, nullable=false)
    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Product_idProduct", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="imageUrl", length=510)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="imageDesc", length=45)
    public String getImageDesc() {
        return this.imageDesc;
    }
    
    public void setImageDesc(String imageDesc) {
        this.imageDesc = imageDesc;
    }




}


