// default package
// Generated Mar 10, 2023, 1:36:13 PM by Hibernate Tools 6.0.0.Alpha3
package iti.jets.marketplace.models;

import java.util.HashSet;
import java.util.Set;

import iti.jets.marketplace.models.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
    ,catalog="marketplacedb"
)
public class Roles  implements java.io.Serializable {


     private Integer rolesId;
     private User user;
     private String name;
     private String description;
     private Set<Authorities> authoritieses = new HashSet<Authorities>(0);

    public Roles() {
    }

	
    public Roles(User user) {
        this.user = user;
    }
    public Roles(User user, String name, String description, Set<Authorities> authoritieses) {
       this.user = user;
       this.name = name;
       this.description = description;
       this.authoritieses = authoritieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rolesId", unique=true, nullable=false)
    public Integer getRolesId() {
        return this.rolesId;
    }
    
    public void setRolesId(Integer rolesId) {
        this.rolesId = rolesId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_userId", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="name", length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="roles_has_authorities", catalog="marketplacedb", joinColumns = { 
        @JoinColumn(name="Roles_rolesId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="authorities_autoritiesId", nullable=false, updatable=false) })
    public Set<Authorities> getAuthoritieses() {
        return this.authoritieses;
    }
    
    public void setAuthoritieses(Set<Authorities> authoritieses) {
        this.authoritieses = authoritieses;
    }




}


