// default package
// Generated Mar 9, 2023, 5:50:18 PM by Hibernate Tools 6.0.0.Alpha3
package iti.jets.marketplace.models;

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Userorderproduct generated by hbm2java
 */
@Entity
@Table(name="userorderproduct"
    ,catalog="marketplacedb"
)
public class Userorderproduct  implements java.io.Serializable {


     private Integer userorderproductId;
     private Product product;
     private User user;
     private String status;
     private Integer productCount;
     private Date orderDate;

    public Userorderproduct() {
    }

	
    public Userorderproduct(Product product, User user) {
        this.product = product;
        this.user = user;
    }
    public Userorderproduct(Product product, User user, String status, Integer productCount, Date orderDate) {
       this.product = product;
       this.user = user;
       this.status = status;
       this.productCount = productCount;
       this.orderDate = orderDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="userorderproductId", unique=true, nullable=false)
    public Integer getUserorderproductId() {
        return this.userorderproductId;
    }
    
    public void setUserorderproductId(Integer userorderproductId) {
        this.userorderproductId = userorderproductId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productId", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userId", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="productCount")
    public Integer getProductCount() {
        return this.productCount;
    }
    
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orderDate", length=19)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }




}


